name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 11s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Balajii-Codoid
          repo: Demo-QA
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: maven.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
